---
title: "StroopE1"
author: "Matt Crump"
date: "August 2, 2016"
output:
  html_document:
    toc: yes
---

```{r,echo=FALSE,message=FALSE,error=FALSE,warning=FALSE}
library(ggplot2)
library(Crump)
library(heplots)
library(Hmisc)
library(plyr)
library(tidyr)
library(pander)
library(xtable)
library(etable)
require(knitr)
library(xlsx)
library(pwr)
```

# E1 Typing and Button Responses

## Transfer Items RT ANOVA

```{r,,echo=FALSE}
setwd("~/Dropbox/Research/ManuscriptsPublications/2016 CrumpBrosowskyMilliken QJEP/Analysis/Stroop/StroopRepository")
AllData<-read.table("StroopE1.csv",sep=",",header=TRUE)

#exclusion
AllData<-AllData[AllData$RT<5000,] #exclude all trials with RT greater than 10000ms
AllData<-AllData[AllData$RT>100,] #exclude all trials with RT less than 100ms
AllData<-AllData[AllData$Error==0,] #exclude all error trials
AllData$Trial[AllData$Trial<(96*2)]<-"First"
AllData$Trial[AllData$Trial!="First"]<-"Last"
AllData$Exp<-factor(AllData$Exp)
AllData$Trial<-factor(AllData$Trial)
AllData$Subject<-factor(AllData$Subject)

#conduct Van Selst & Jolicouer outlier elimination
AllData<-ddply(AllData, .(Subject,Exp,Trial,Context,Proportion,Congruency),summarise,meanRT=mean(vjout(RT)$data),removed=vjout(RT)$pr)

#Proportion of outliers removed from each condition
#1-mean(AllData$removed)

#Analyse only Transfer items
AllData<-AllData[AllData$Context=="Transfer",] 

#Run ANOVA
aov.out<-aov(meanRT~Exp*Trial*Proportion*Congruency + Error(Subject/(Trial*Proportion*Congruency)),AllData)
kable(xtable(aov.out),format="markdown")

```

### Stroop and CSPC effects

```{r,echo=FALSE}
# Get means and SEs to build table

SubjectStroop <-  ddply(AllData,.(Subject,Exp,Trial,Proportion),summarise,
                  Stroop=meanRT[Congruency=="Inc"]-meanRT[Congruency=="Con"])

SubjectCSPC   <-  ddply(AllData,.(Subject,Exp,Trial),summarise,
                  CSPC=(meanRT[Proportion=="High" & Congruency=="Inc"]-
                    meanRT[Proportion=="High" & Congruency=="Con"])-
                    (meanRT[Proportion=="Low" & Congruency=="Inc"]-
                    meanRT[Proportion=="Low" & Congruency=="Con"]))

AllStroop     <-  ddply(SubjectStroop,.(Exp,Trial,Proportion),summarise,
                        mStroop=mean(Stroop),seStroop=stde(Stroop))

AllCSPC     <-  ddply(SubjectCSPC,.(Exp,Trial),summarise,
                        mCSPC=mean(CSPC),seCSPC=stde(CSPC))


kable(xtable(AllStroop),format="markdown")
write.xlsx(AllStroop,file="e1.xlsx",sheetName="Sheet2")

kable(xtable(AllCSPC),format="markdown")
write.xlsx(AllCSPC,file="e1.xlsx",sheetName="Sheet3",append=TRUE)

##for power analysis

SubPC<-ddply(AllData,.(Subject,Proportion,Congruency),summarise,RTs=mean(meanRT))

SubCSPC<-ddply(SubPC,.(Subject),summarise,
                  CSPC=(RTs[Proportion=="High" & Congruency=="Inc"]-
                    RTs[Proportion=="High" & Congruency=="Con"])-
                    (RTs[Proportion=="Low" & Congruency=="Inc"]-
                    RTs[Proportion=="Low" & Congruency=="Con"]))

mean(SubCSPC$CSPC)
Sigma<-sd(SubCSPC$CSPC)
N=dim(SubCSPC)[1]
pout<-pwr.t.test(n = N, d = NULL, sig.level = 0.05, power = .8, 
           type = "one.sample",
           alternative = "two.sided")
D<-pout$d
pout
Sigma
D*Sigma

```

### Mean RTs

```{r,echo=FALSE}

MeanAllData<-ddply(AllData,.(Exp,Trial,Context,Proportion,Congruency),summarise,RTs=mean(meanRT),SErt=stde(meanRT))
MeanAllData

MeanAllData<-ddply(AllData,.(Trial,Proportion,Congruency),summarise,RTs=mean(meanRT),SErt=stde(meanRT))
MeanAllData

CSPCFirst<-(MeanAllData[MeanAllData$Trial=="First" & MeanAllData$Proportion=="High" & MeanAllData$Congruency=="Inc",]$RT-
              MeanAllData[MeanAllData$Trial=="First" & MeanAllData$Proportion=="High" & MeanAllData$Congruency=="Con",]$RT)-
            (MeanAllData[MeanAllData$Trial=="First" & MeanAllData$Proportion=="Low" & MeanAllData$Congruency=="Inc",]$RT-
              MeanAllData[MeanAllData$Trial=="First" & MeanAllData$Proportion=="Low" & MeanAllData$Congruency=="Con",]$RT)
CSPCFirst

CSPCLast<-(MeanAllData[MeanAllData$Trial=="Last" & MeanAllData$Proportion=="High" & MeanAllData$Congruency=="Inc",]$RT-
              MeanAllData[MeanAllData$Trial=="Last" & MeanAllData$Proportion=="High" & MeanAllData$Congruency=="Con",]$RT)-
            (MeanAllData[MeanAllData$Trial=="Last" & MeanAllData$Proportion=="Low" & MeanAllData$Congruency=="Inc",]$RT-
              MeanAllData[MeanAllData$Trial=="Last" & MeanAllData$Proportion=="Low" & MeanAllData$Congruency=="Con",]$RT)
CSPCLast
  
```

### Means

```{r,echo=FALSE}

MeanAllData<-ddply(AllData,.(Trial),summarise,RTs=mean(meanRT),SErt=stde(meanRT))
MeanAllData

MeanAllData<-ddply(AllData,.(Congruency),summarise,RTs=mean(meanRT),SErt=stde(meanRT))
MeanAllData

MeanAllData<-ddply(AllData,.(Exp,Congruency),summarise,RTs=mean(meanRT),SErt=stde(meanRT))
MeanAllData

StroopTyping<-MeanAllData[MeanAllData$Exp=="Typing" & MeanAllData$Congruency=="Inc",]$RT-
            MeanAllData[MeanAllData$Exp=="Typing" & MeanAllData$Congruency=="Con",]$RT
StroopTyping

StroopButton<-MeanAllData[MeanAllData$Exp=="Button" & MeanAllData$Congruency=="Inc",]$RT-
           MeanAllData[MeanAllData$Exp=="Button" & MeanAllData$Congruency=="Con",]$RT
StroopButton

MeanAllData<-ddply(AllData,.(Trial,Congruency),summarise,RTs=mean(meanRT),SErt=stde(meanRT))
MeanAllData

StroopFirst<-MeanAllData[MeanAllData$Trial=="First" & MeanAllData$Congruency=="Inc",]$RT-
            MeanAllData[MeanAllData$Trial=="First" & MeanAllData$Congruency=="Con",]$RT
StroopFirst

StroopLast<-MeanAllData[MeanAllData$Trial=="Last" & MeanAllData$Congruency=="Inc",]$RT-
          MeanAllData[MeanAllData$Trial=="Last" & MeanAllData$Congruency=="Con",]$RT
StroopLast

MeanAllData<-ddply(AllData,.(Exp,Trial,Proportion,Congruency),summarise,RTs=mean(meanRT),SErt=stde(meanRT))
MeanAllDataRT<-MeanAllData
kable(xtable(MeanAllData),format="markdown")




#For Button
StroopFirst<-MeanAllData[MeanAllData$Exp=="Button" & MeanAllData$Trial=="First" & MeanAllData$Congruency=="Inc",]$RT-
            MeanAllData[MeanAllData$Exp=="Button" &MeanAllData$Trial=="First" & MeanAllData$Congruency=="Con",]$RT
StroopFirst

StroopLast<-MeanAllData[MeanAllData$Exp=="Button" &MeanAllData$Trial=="Last" & MeanAllData$Congruency=="Inc",]$RT-
          MeanAllData[MeanAllData$Exp=="Button" &MeanAllData$Trial=="Last" & MeanAllData$Congruency=="Con",]$RT
StroopLast

#For Typing
StroopFirst<-MeanAllData[MeanAllData$Exp=="Typing" & MeanAllData$Trial=="First" & MeanAllData$Congruency=="Inc",]$RT-
            MeanAllData[MeanAllData$Exp=="Typing" &MeanAllData$Trial=="First" & MeanAllData$Congruency=="Con",]$RT
StroopFirst

StroopLast<-MeanAllData[MeanAllData$Exp=="Typing" &MeanAllData$Trial=="Last" & MeanAllData$Congruency=="Inc",]$RT-
          MeanAllData[MeanAllData$Exp=="Typing" &MeanAllData$Trial=="Last" & MeanAllData$Congruency=="Con",]$RT
StroopLast



```

## Transfer Items Error Rates ANOVA

```{r,echo=FALSE}
AllData<-read.table("StroopE1.csv",sep=",",header=TRUE)
AllData<-AllData[AllData$RT<5000,] #exclude all trials with RT greater than 10000ms
#AllData<-AllData[AllData$RT>100,] #exclude all trials with RT less than 100ms
#AllData<-AllData[AllData$Error==0,] #exclude all error trials
AllData$Trial[AllData$Trial<(96*2)]<-"First"
AllData$Trial[AllData$Trial!="First"]<-"Last"
AllData$Exp<-factor(AllData$Exp)
AllData$Trial<-factor(AllData$Trial)
AllData$Subject<-factor(AllData$Subject)

#conduct Van Selst & Jolicouer outlier elimination
AllData<-ddply(AllData, .(Subject,Exp,Trial,Context,Proportion,Congruency),summarise,meanER=mean(Error))

#Analyse only Transfer items
AllData<-AllData[AllData$Context=="Transfer",] 

#Run ANOVA
aov.out<-aov(meanER~Exp*Trial*Proportion*Congruency + Error(Subject/(Trial*Proportion*Congruency)),AllData)
kable(xtable(aov.out),format="markdown")
```

## Tabular Report: Mean RT and Errors in 

```{r,echo=FALSE}
MeanAllData<-ddply(AllData,.(Exp,Trial,Context,Proportion,Congruency),summarise,ERs=mean(meanER))
MeanAllDataRT<-cbind(MeanAllDataRT,ER=MeanAllData$ERs)

Tab <- tabular.ade(x_vars=c('MEAN'), rows=c('Exp','Trial','Proportion'), rnames= c('Experiment','Half','Proportion'), y_vars=c('RTs','SErt','ER'),cols=c('Congruency'),cnames='Congruency',data=MeanAllDataRT, FUN=stat_cell)

#xtable(Tab)
kable(xtable(Tab),format="markdown")
#write.xlsx(Tab,file="e1.xlsx",sheetName="Sheet1",append=TRUE)
#write.csv(Tab, file="e1out.csv",append=TRUE)

#xtable(MeanAllData)
#mean(MeanAllData$ERs)
```
